swagger: '2.0'
info:
  title: AVEC Restauration API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/register:
    post:
      tags:
        - User Module
      summary: Register
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/update/:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Edit User Profile
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/deleteUser/{userId}:
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete user
      description: API for deleting a transaction
      parameters:
        - in: path
          name: "userId"
          description: The profile id, as a string
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /plats/:
    get:
      tags:
        - Plats Module
      summary: Plats
      description: API for fetching plats
      produces:
        - application/json
      responses:
        '200':
          description: Plats Fetched Successfully
          schema:
            $ref: '#/definitions/Plats'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      tags:
        - Plats Module
      summary: Add Plat
      description: API for adding plat
      produces:
        - application/json
      responses:
        '200':
          description: Plat added Successfully
          schema:
            $ref: '#/definitions/Plats'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /plats/{platId}:
    get:
      tags:
        - Plats Module
      summary: Plat
      description: API for fetching plats
      parameters:
        - in: path
          name: "platId"
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Plats Fetched Successfully
          schema:
            $ref: '#/definitions/Plats'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Aliments Module
      summary: Edit Plat
      description: API for editing plat info
      parameters:
        - in: path
          name: "platId"
          description: The plat id, as a string
          required: true
          type : string
          schema:
            $ref: '#/definitions/Plats'
      produces:
        - application/json
      responses:
        '201':
          description: Plat info edited successully
          schema:
            $ref: '#/definitions/Plats'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Plats Module
      summary:  Delete plat
      description: API for deleting a plat
      parameters:
        - in: path
          name: "platId"
          description: The plat id, as a string
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Plat deleted successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /aliments/:
    get:
      tags:
        - Aliments Module
      summary: Aliments
      description: API for fetching aliments
      produces:
        - application/json
      responses:
        '200':
          description: Aliments Fetched Successfully
          schema:
            $ref: '#/definitions/Aliments'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      tags:
        - Aliments Module
      summary: Add aliment
      description: API for adding aliments
      produces:
        - application/json
      responses:
        '200':
          description: Aliments added Successfully
          schema:
            $ref: '#/definitions/Aliments'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /aliments/{alimentId}:
    get:
      tags:
        - Aliments Module
      summary: Aliment
      description: API for fetching aliments
      parameters:
        - in: path
          name: "alimentId"
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Aliments Fetched Successfully
          schema:
            $ref: '#/definitions/Aliments'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Aliments Module
      summary: Edit aliment
      description: API for editing aliment info
      parameters:
        - in: path
          name: "alimentId"
          description: The aliment id, as a string
          required: true
          type : string
          schema:
            $ref: '#/definitions/Aliments'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction info added successully
          schema:
            $ref: '#/definitions/Aliments'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Aliments Module
      summary: Delete aliment
      description: API for deleting a aliment
      parameters:
        - in: path
          name: "alimentId"
          description: The aliment id, as a string
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: Aliment deleted successully
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  Plats:
    type: object
  PlatId:
    properties :
      PlatId :
        type : string
  Aliments:
    type: object
  AlimentId :
    properties :
      alimentId :
        type : string
